# Generated by scripts/render_vault.py. Do not grant list or wildcard access.

path "kv/data/n8n/mattermost/checkin/dialog-shared" {
  capabilities = ["read"]
}

path "kv/data/n8n/mattermost/checkin/open" {
  capabilities = ["read"]
}
